language: java
jdk:
  - openjdk8

branche:
  only:
    - master

# Travis CI 서버의 Home
#cache:
  #directories:

script: mvn clean package

# CI 실행 완료시 메일
notifications:
  email:
    recipients:
      - micky3073@naver.com

before_deploy:
  - zip -r Spring_Web_Service *
  - mkdir -p deploy
  - mv Spring_Web_Servce.zip deploy/Spring_Web_Servce.zip


deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY 
    bucket: spring-webservice-deployment
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Minoolian/Spring_Web_Service
      branch: master
