language: java
jdk:
  - openjdk8

branche:
  only:
    - master

# Travis CI 서버의 Home
#cache:
  #directories:

script: mvn clean package

before_deploy:
  - zip -r Spring_Web_Service *
  - mkdir -p deploy
  - mv Spring_Web_Service.zip deploy/Spring_Web_Service.zip


deploy:
  - provider: s3
    local_dir: deploy
    access_key_id: $AWS_ACCESS_KEY 
    secret_access_key: $AWS_SECRET_KEY 
    bucket: spring-webservice-deployment
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: Minoolian/Spring_Web_Service
      branch: master

  #- provider: codedeploy
  #  access_key_id: $AWS_ACCESS_KEY 
  #  secret_access_key: $AWS_SECRET_KEY 
  #  bucket: spring-webservice-deployment 
  #  key: Spring_Web_Service.zip 
  #  bundle_type: zip
  #  application: spring-webservice 
  #  deployment_group: spring-webservice-group
  #  region: ap-northeast-2
  #  wait-until-deployed: true
  #  on:
  #    repo: Minoolian/Spring_Web_Service
  #    branch: master
  
notifications:
  email:
    recipients:
      - micky3073@naver.com
